"use client"

import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
} from "react"

export type Locale = "lo" | "en"

const translations = {
  lo: {
    adminPanel: "ໜ້າຈັດການ",
    bookNow: "ຈອງຫ້ອງ",
    bookingLabel: "ຈອງຫ້ອງ",
    checkIn: "ວັນທີເຂົ້າພັກ",
    checkOut: "ວັນທີເຊັກເອົາ",
    chooseThisRoom: "ເລືອກຫ້ອງນີ້",
    featured: "ແນະນຳ",
    heroKicker: "ຍິນດີຕ້ອນຮັບ",
    languageEnglish: "English",
    languageLao: "ລາວ",
    languageSwitcher: "ປ່ຽນພາສາ",
    navHistory: "ປະຫວັດການຈອງ",
    navLogin: "ເຂົ້າລະບົບ",
    navLogout: "ອອກຈາກລະບົບ",
    navProfile: "ໂປຣໄຟລ໌",
    navSignIn: "ເຂົ້າລະບົບ",
    navSignUp: "ສະໝັກສະມາຊິກ",
    noRooms: "ບໍ່ພົບຫ້ອງທີ່ຄົ້ນຫາ",
    people: "ຄົນ",
    roomsCountSuffix: "ຫ້ອງ",
    roomsTitle: "ຫ້ອງພັກ",
    searchPlaceholder: "ຄົ້ນຫາ...",
    selectRoom: "ເລືອກຫ້ອງ",
    all: "ທັງໝົດ",
    refresh: "ໂຫຼດໃໝ່",
    dashboard: "ໜ້າຫຼັກ",
    roomStatus: "ສະຖານະຫ້ອງ",
    bookingManagement: "ຈັດການການຈອງ",
    checkInOut: "ເຂົ້າພັກ / ອອກພັກ",
    cancellationsRefunds: "ຍົກເລີກ / ຄືນເງິນ",
    guests: "ລາຍຊື່ແຂກ",
    reviewsManagement: "ຈັດການຣີວິວ",
    users: "ຜູ້ໃຊ້",
    staff: "ພະນັກງານ",
    rooms: "ຫ້ອງພັກ",
    roomType: "ປະເພດຫ້ອງ",
    priceConfig: "ຕັ້ງຄ່າລາຄາ",
    reports: "ລາຍງານ",
    accessLogs: "ປະຫວັດເຂົ້າລະບົບ",
    roomStatusSubtitle: "ອັບເດດສະຖານະການທຳຄວາມສະອາດ ແລະ ຄວາມພ້ອມໃຊ້ຂອງຫ້ອງ.",
    statusAvailable: "ວ່າງ",
    statusOccupied: "ມີຜູ້ພັກ",
    statusMaintenance: "ສ້ອມແປງ",
    statusReserved: "ຈອງແລ້ວ",
    statusPending: "ລໍຖ້າ",
    statusApproved: "ອະນຸມັດແລ້ວ",
    statusRejected: "ປະຕິເສດ",
    statusConfirmed: "ຢືນຢັນແລ້ວ",
    statusCheckedIn: "ເຂົ້າພັກແລ້ວ",
    statusCheckedOut: "ອອກພັກແລ້ວ",
    statusCompleted: "ສຳເລັດ",
    statusCancelled: "ຍົກເລີກ",
    statusNoShow: "ບໍ່ມາພັກ",
    room: "ຫ້ອງ",
    name: "ຊື່",
    type: "ປະເພດ",
    current: "ປັດຈຸບັນ",
    changeStatus: "ປ່ຽນສະຖານະ",
    capacity: "ຈຳນວນຄົນ",
    searchRoom: "ຄົ້ນຫາຫ້ອງ...",
    searchGuest: "ຄົ້ນຫາແຂກ...",
    noRoomsFound: "ບໍ່ພົບຫ້ອງ",
    noGuestsFound: "ບໍ່ພົບແຂກ",
    guestsSubtitle: "ປະຫວັດແຂກ, ຍອດໃຊ້ຈ່າຍ ແລະ ປະຫວັດບໍ່ມາພັກ ສຳລັບພະນັກງານຕ້ອນຮັບ.",
    hasNoShow: "ມີປະຫວັດບໍ່ມາພັກ",
    contact: "ຕິດຕໍ່",
    joined: "ວັນທີສະໝັກ",
    bookings: "ການຈອງ",
    stays: "ເຂົ້າພັກ",
    noShow: "ບໍ່ມາພັກ",
    cancelled: "ຍົກເລີກ",
    totalSpent: "ຍອດໃຊ້ຈ່າຍລວມ",
    lastStay: "ເຂົ້າພັກຫຼ້າສຸດ",
    cancellationsSubtitle: "ກວດຄຳຮ້ອງຍົກເລີກ, ອະນຸມັດເງິນຄືນ ແລະ ຢືນຢັນການໂອນ.",
    refundsToTransfer: "ເງິນຄືນທີ່ຕ້ອງໂອນ",
    noCancellationRequests: "ບໍ່ມີຄຳຮ້ອງຍົກເລີກ",
    reason: "ເຫດຜົນ",
    bookingTotal: "ຍອດຈອງລວມ",
    refund: "ເງິນຄືນ",
    approve: "ອະນຸມັດ",
    reject: "ປະຕິເສດ",
    refunded: "ຄືນເງິນແລ້ວ",
    uploadSlip: "ອັບໂຫຼດສະລິບ",
    viewSlip: "ເບິ່ງສະລິບ",
    viewRefundQr: "ເບິ່ງ QR ຮັບເງິນຄືນ",
    noTransferNeeded: "ບໍ່ຕ້ອງໂອນເງິນ",
    actioned: "ດຳເນີນການແລ້ວ",
    missingRefundAccount: "ລູກຄ້າຍັງບໍ່ໃສ່ບັນຊີຮັບເງິນຄືນ / QR",
    noRefund: "ບໍ່ມີເງິນຄືນ (ຍັງບໍ່ຈ່າຍ / ບໍ່ເຂົ້າເງື່ອນໄຂ)",
    confirmRejectCancellation: "ຢືນຢັນປະຕິເສດຄຳຮ້ອງຍົກເລີກນີ້ບໍ?",
    frontDeskSubtitle: "ລາຍການວຽກພະນັກງານຕ້ອນຮັບ — ແຂກທີ່ຕ້ອງເຂົ້າພັກ ແລະ ແຂກທີ່ຕ້ອງອອກພັກ.",
    worklist: "ລາຍການວຽກ",
    history: "ປະຫວັດ",
    arrivals: "ເຂົ້າພັກມື້ນີ້",
    inHouse: "ກຳລັງພັກ",
    noArrivals: "ບໍ່ມີແຂກເຂົ້າພັກ",
    noInHouse: "ບໍ່ມີແຂກກຳລັງພັກ",
    noCheckHistory: "ບໍ່ມີປະຫວັດເຂົ້າ/ອອກພັກ",
    action: "ການດຳເນີນການ",
    time: "ເວລາ",
    admin: "ແອດມິນ",
    checkInAction: "ເຂົ້າພັກ",
    checkOutAction: "ອອກພັກ",
    confirmCheckIn: "ຢືນຢັນເຂົ້າພັກ",
    confirmCheckOutQuestion: "ຢືນຢັນໃຫ້ແຂກຄົນນີ້ອອກພັກບໍ?",
    dueToCheckOut: "ຮອດກຳນົດອອກພັກ",
    payAtHotel: "ຈ່າຍທີ່ໂຮງແຮມ",
    collectCash: "ເກັບເງິນສົດ",
    checkingInMarksPaid: "ເມື່ອເຂົ້າພັກແລ້ວ ລະບົບຈະຖືວ່າຊຳລະແລ້ວ.",
    paid: "ຊຳລະແລ້ວ",
    documentType: "ປະເພດເອກະສານ",
    documentNo: "ເລກທີ່ເອກະສານ",
    idCard: "ບັດປະຊາຊົນ",
    passport: "ພາສປອດ",
    other: "ອື່ນໆ",
    nationality: "ສັນຊາດ",
    docExpiry: "ວັນໝົດອາຍຸ",
    remarks: "ໝາຍເຫດ",
    optional: "ທາງເລືອກ",
    documentPhoto: "ຮູບເອກະສານ",
    uploadTakePhoto: "ອັບໂຫຼດ / ຖ່າຍຮູບ",
    cancel: "ຍົກເລີກ",
    greeting: "ສະບາຍດີ",
    pendingItems: "ມີລາຍການລໍຖ້າ",
    items: "ລາຍການ",
    roomOverview: "ສະຖານະຫ້ອງ",
    bookingOverview: "ການຈອງ",
    financeOther: "ການເງິນ & ອື່ນໆ",
    totalRooms: "ຫ້ອງທັງໝົດ",
    inUseNow: "ໃຊ້ງານຕອນນີ້",
    todayCheckIn: "ເຂົ້າພັກມື້ນີ້",
    todayCheckOut: "ອອກພັກມື້ນີ້",
    monthlyRevenue: "ລາຍໄດ້ເດືອນນີ້",
    pendingPaymentVerify: "ລໍຢືນຢັນຊຳລະ",
    pendingReviews: "ຣີວິວລໍກວດ",
    systemUsers: "ຜູ້ໃຊ້ລະບົບ",
    occupancyRate: "ອັດຕາເຂົ້າພັກ",
    recentBookings: "ການຈອງຫຼ້າສຸດ",
    viewAll: "ເບິ່ງທັງໝົດ",
    booker: "ຜູ້ຈອງ",
    date: "ວັນທີ",
    price: "ລາຄາ",
    status: "ສະຖານະ",
    noBookingsYet: "ຍັງບໍ່ມີການຈອງ",
    reviewStay: "ຣີວິວການເຂົ້າພັກ",
    tellUsAboutStay: "ບອກພວກເຮົາກ່ຽວກັບການເຂົ້າພັກຂອງທ່ານ...",
    submit: "ສົ່ງ",
    review: "ຣີວິວ",
    editReview: "ແກ້ໄຂຣີວິວ",
    ratingError: "ຄະແນນຕ້ອງຢູ່ລະຫວ່າງ 1 ຫາ 5",
    reviewSubmitError: "ສົ່ງຣີວິວບໍ່ສຳເລັດ",
    accountSettings: "ຕັ້ງຄ່າບັນຊີ",
    accountDetails: "ຂໍ້ມູນບັນຊີ ແລະ ການຕັ້ງຄ່າຂອງທ່ານ.",
    fullName: "ຊື່ເຕັມ",
    email: "ອີເມວ",
    phone: "ເບີໂທ",
    role: "ສິດທິ",
    accountId: "ເລກບັນຊີ",
    memberSince: "ເປັນສະມາຊິກຕັ້ງແຕ່",
    editProfile: "ແກ້ໄຂໂປຣໄຟລ໌",
    superAdminDashboard: "ໜ້າຫຼັກ SuperAdmin",
    systemOverview: "ພາບລວມລະບົບ",
    admins: "ແອດມິນ",
    latestAccessLogs: "ປະຫວັດເຂົ້າລະບົບຫຼ້າສຸດ",
    login: "ເຂົ້າລະບົບ",
    logout: "ອອກລະບົບ",
    ipAddress: "IP",
    accessLogsSubtitle: "ບັນທຶກການເຂົ້າລະບົບຫຼ້າສຸດສຳລັບກວດສອບ.",
    noAccessLogs: "ບໍ່ພົບປະຫວັດເຂົ້າລະບົບ",
    topRoomsByBookings: "ຫ້ອງຍອດນິຍົມ (ຕາມການຈອງ)",
    manageAllUsers: "ຈັດການຜູ້ໃຊ້ທັງໝົດ",
    userRole: "ຜູ້ໃຊ້",
    adminRole: "ແອດມິນ",
    superAdminRole: "SuperAdmin",
    joinedAt: "ສະໝັກເມື່ອ",
    noData: "ບໍ່ມີຂໍ້ມູນ",
    you: "ທ່ານ",
    changeRole: "ປ່ຽນສິດທິ",
    confirmChangeRole: "ຢືນຢັນປ່ຽນສິດທິເປັນ",
    deleteUser: "ລຶບຜູ້ໃຊ້",
    confirmDeleteUser: "ຢືນຢັນລຶບຜູ້ໃຊ້ນີ້ບໍ?",
    add: "ເພີ່ມ",
    edit: "ແກ້ໄຂ",
    save: "ບັນທຶກ",
    saving: "ກຳລັງບັນທຶກ...",
    active: "ໃຊ້ງານ",
    inactive: "ປິດໃຊ້ງານ",
    disable: "ປິດໃຊ້ງານ",
    addRoomType: "ເພີ່ມປະເພດຫ້ອງ",
    editRoomType: "ແກ້ໄຂປະເພດຫ້ອງ",
    roomTypeSubtitle: "ຈັດການປະເພດຫ້ອງ ແລະ ລາຄາພື້ນຖານ.",
    typeName: "ຊື່ປະເພດ",
    basePrice: "ລາຄາພື້ນຖານ",
    maxGuests: "ຈຳນວນແຂກສູງສຸດ",
    imagesUrl: "ຮູບພາບ (URL)",
    amenities: "ສິ່ງອຳນວຍຄວາມສະດວກ",
    description: "ລາຍລະອຽດ",
    searchType: "ຄົ້ນຫາປະເພດ...",
    noRoomTypesFound: "ບໍ່ພົບປະເພດຫ້ອງ",
    addPriceConfig: "ເພີ່ມການຕັ້ງຄ່າລາຄາ",
    editPriceConfig: "ແກ້ໄຂການຕັ້ງຄ່າລາຄາ",
    priceConfigSubtitle: "ລາຄາຕາມລະດູການແຍກຕາມປະເພດຫ້ອງ. Priority ສູງກວ່າຈະຖືກໃຊ້ກ່ອນ.",
    season: "ລະດູການ",
    seasonName: "ຊື່ລະດູການ",
    selectRoomType: "ເລືອກປະເພດຫ້ອງ",
    priority: "Priority",
    startDate: "ວັນເລີ່ມ",
    endDate: "ວັນສິ້ນສຸດ",
    dateRange: "ຊ່ວງວັນທີ",
    noPriceConfigsFound: "ບໍ່ພົບການຕັ້ງຄ່າລາຄາ",
    run: "ປະມວນຜົນ",
    print: "ພິມ",
    validationMissingBookingInfo: "ກະລຸນາເລືອກຫ້ອງ ແລະ ວັນທີໃຫ້ຄົບ",
  },
  en: {
    adminPanel: "Admin Panel",
    bookNow: "Book Now",
    bookingLabel: "Booking",
    checkIn: "Check-in",
    checkOut: "Check-out",
    chooseThisRoom: "Choose this room",
    featured: "Featured",
    heroKicker: "Welcome to",
    languageEnglish: "English",
    languageLao: "Lao",
    languageSwitcher: "Change language",
    navHistory: "Booking History",
    navLogin: "Login",
    navLogout: "Logout",
    navProfile: "Profile",
    navSignIn: "Sign In",
    navSignUp: "Sign Up",
    noRooms: "No rooms found",
    people: "people",
    roomsCountSuffix: "rooms",
    roomsTitle: "Rooms",
    searchPlaceholder: "Search...",
    selectRoom: "Select room",
    all: "All",
    refresh: "Refresh",
    dashboard: "Dashboard",
    roomStatus: "Room Status",
    bookingManagement: "Bookings",
    checkInOut: "Check-in / out",
    cancellationsRefunds: "Cancellations / Refunds",
    guests: "Guests",
    reviewsManagement: "Reviews",
    users: "Users",
    staff: "Staff",
    rooms: "Rooms",
    roomType: "Room Type",
    priceConfig: "Price Config",
    reports: "Reports",
    accessLogs: "Access Logs",
    roomStatusSubtitle: "Update housekeeping and availability status.",
    statusAvailable: "Available",
    statusOccupied: "Occupied",
    statusMaintenance: "Maintenance",
    statusReserved: "Reserved",
    statusPending: "Pending",
    statusApproved: "Approved",
    statusRejected: "Rejected",
    statusConfirmed: "Confirmed",
    statusCheckedIn: "Checked in",
    statusCheckedOut: "Checked out",
    statusCompleted: "Completed",
    statusCancelled: "Cancelled",
    statusNoShow: "No-show",
    room: "Room",
    name: "Name",
    type: "Type",
    current: "Current",
    changeStatus: "Change Status",
    capacity: "Capacity",
    searchRoom: "Search room...",
    searchGuest: "Search guest...",
    noRoomsFound: "No rooms found",
    noGuestsFound: "No guests found",
    guestsSubtitle: "Guest history, spending and no-show record for the front desk.",
    hasNoShow: "Has no-show",
    contact: "Contact",
    joined: "Joined",
    bookings: "Bookings",
    stays: "Stays",
    noShow: "No-show",
    cancelled: "Cancelled",
    totalSpent: "Total Spent",
    lastStay: "Last Stay",
    cancellationsSubtitle: "Review cancellation requests, approve refunds, and confirm bank transfers.",
    refundsToTransfer: "Refunds to transfer",
    noCancellationRequests: "No cancellation requests",
    reason: "Reason",
    bookingTotal: "Booking total",
    refund: "Refund",
    approve: "Approve",
    reject: "Reject",
    refunded: "Refunded",
    uploadSlip: "Upload slip",
    viewSlip: "View slip",
    viewRefundQr: "View refund QR",
    noTransferNeeded: "No transfer needed",
    actioned: "Actioned",
    missingRefundAccount: "Missing refund account / QR from customer",
    noRefund: "No refund (unpaid / non-refundable)",
    confirmRejectCancellation: "Reject this cancellation request?",
    frontDeskSubtitle: "Front-desk worklist — arrivals to check in and guests due to check out.",
    worklist: "Worklist",
    history: "History",
    arrivals: "Arrivals",
    inHouse: "In-house",
    noArrivals: "No arrivals to check in",
    noInHouse: "No guests in house",
    noCheckHistory: "No check-in/out history",
    action: "Action",
    time: "Time",
    admin: "Admin",
    checkInAction: "Check in",
    checkOutAction: "Check out",
    confirmCheckIn: "Confirm check-in",
    confirmCheckOutQuestion: "Check this guest out?",
    dueToCheckOut: "Due to check out",
    payAtHotel: "Pay at hotel",
    collectCash: "Collect cash",
    checkingInMarksPaid: "Checking in marks it paid.",
    paid: "Paid",
    documentType: "Document type",
    documentNo: "Document no.",
    idCard: "ID Card",
    passport: "Passport",
    other: "Other",
    nationality: "Nationality",
    docExpiry: "Doc expiry",
    remarks: "Remarks",
    optional: "optional",
    documentPhoto: "Document photo",
    uploadTakePhoto: "Upload / take a photo",
    cancel: "Cancel",
    greeting: "Hello",
    pendingItems: "Pending items",
    items: "items",
    roomOverview: "Room status",
    bookingOverview: "Bookings",
    financeOther: "Finance & other",
    totalRooms: "Total rooms",
    inUseNow: "In use now",
    todayCheckIn: "Check-in today",
    todayCheckOut: "Check-out today",
    monthlyRevenue: "Revenue this month",
    pendingPaymentVerify: "Pending payment verify",
    pendingReviews: "Pending reviews",
    systemUsers: "System users",
    occupancyRate: "Occupancy Rate",
    recentBookings: "Recent bookings",
    viewAll: "View all",
    booker: "Booker",
    date: "Date",
    price: "Price",
    status: "Status",
    noBookingsYet: "No bookings yet",
    reviewStay: "Review your stay",
    tellUsAboutStay: "Tell us about your stay...",
    submit: "Submit",
    review: "Review",
    editReview: "Edit review",
    ratingError: "Rating must be between 1 and 5",
    reviewSubmitError: "Failed to submit review",
    accountSettings: "Account Settings",
    accountDetails: "Your account details and preferences.",
    fullName: "Full name",
    email: "Email",
    phone: "Phone",
    role: "Role",
    accountId: "Account ID",
    memberSince: "Member since",
    editProfile: "Edit profile",
    superAdminDashboard: "SuperAdmin Dashboard",
    systemOverview: "System overview",
    admins: "Admins",
    latestAccessLogs: "Latest access logs",
    login: "Login",
    logout: "Logout",
    ipAddress: "IP",
    accessLogsSubtitle: "Latest login records for audit review.",
    noAccessLogs: "No access logs found",
    topRoomsByBookings: "Top Rooms (by bookings)",
    manageAllUsers: "Manage all users",
    userRole: "User",
    adminRole: "Admin",
    superAdminRole: "SuperAdmin",
    joinedAt: "Joined",
    noData: "No data",
    you: "You",
    changeRole: "Change role",
    confirmChangeRole: "Change role to",
    deleteUser: "Delete user",
    confirmDeleteUser: "Delete this user?",
    add: "Add",
    edit: "Edit",
    save: "Save",
    saving: "Saving...",
    active: "Active",
    inactive: "Inactive",
    disable: "Disable",
    addRoomType: "Add Room Type",
    editRoomType: "Edit Room Type",
    roomTypeSubtitle: "Manage room categories and base pricing.",
    typeName: "Type Name",
    basePrice: "Base Price",
    maxGuests: "Max Guests",
    imagesUrl: "Images (URL)",
    amenities: "Amenities",
    description: "Description",
    searchType: "Search type...",
    noRoomTypesFound: "No room types found",
    addPriceConfig: "Add Price Config",
    editPriceConfig: "Edit Price Config",
    priceConfigSubtitle: "Seasonal pricing by room type. Higher priority wins.",
    season: "Season",
    seasonName: "Season Name",
    selectRoomType: "Select room type",
    priority: "Priority",
    startDate: "Start Date",
    endDate: "End Date",
    dateRange: "Date Range",
    noPriceConfigsFound: "No price configs found",
    run: "Run",
    print: "Print",
    validationMissingBookingInfo: "Please select a room and complete the dates",
  },
} as const

export type TranslationKey = keyof typeof translations.lo

type LanguageContextValue = {
  locale: Locale
  setLocale: (locale: Locale) => void
  t: (key: TranslationKey) => string
}

const STORAGE_KEY = "resort-mdnk1-locale"

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>("lo")

  useEffect(() => {
    const stored = window.localStorage.getItem(STORAGE_KEY)
    if (stored !== "lo" && stored !== "en") return
    const timer = window.setTimeout(() => setLocaleState(stored), 0)
    return () => window.clearTimeout(timer)
  }, [])

  const setLocale = useCallback((nextLocale: Locale) => {
    setLocaleState(nextLocale)
    window.localStorage.setItem(STORAGE_KEY, nextLocale)
  }, [])

  useEffect(() => {
    document.documentElement.lang = locale
    document.documentElement.dataset.locale = locale
  }, [locale])

  const value = useMemo<LanguageContextValue>(() => ({
    locale,
    setLocale,
    t: (key) => translations[locale][key] ?? translations.lo[key] ?? key,
  }), [locale, setLocale])

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider")
  }
  return context
}
